### ISSUE TITLE
Press Page 

### ISSUE THREAD

**Issue by omelki** [pro-freelancer/TOB#10]
The footer background went on top of the content when I changed the category names from the dashboard.

If you want have an idea on how to fix that issue check the gallery page coz it has the same layout since both of them comes from the portfolio template.

**Comment by pro-freelancer** [comment]
It is not related to categories names, the issue that you changed the type of templates to colomun-4 instead of portfolio grid, once I put it to portfolio grid, it had the same layout as gallery.

It seems the colomun4 is not working properly due to changes that was made in functions by mohamad. he rewrite the behavior of this option by adding something to main function.php

In case you want to enhance it you can open a new issue , this one is closed.

**Comment by pro-freelancer** [comment]
Best solution was as follow:
replicated the portfolio grid template by naming it press grid.
modify the css so the over effect took same image width 220px;
upload it to the avada-child theme.
choose the template from the backoffice of press page.
issue fixed.

**Comment by omelki** [comment]
Thx for putting an effort into this. However this is not what I have expected, the page layout should look like this link: http://theme-fusion.com/avada/4-column-grid/ 

I should've told you about it before my bad :s

**Comment by pro-freelancer** [comment]
fixed to 4 column instead of 3

**Comment by omelki** [comment]
Yesssss !!! ((:

**Comment by omelki** [comment]
Still some little enhancement to be done, the title text should be beneath each image and not when you hover on it. Plus can you remove the green slliding effect from them. It should be like this: either if you click on the image or the title below it, it will take me to its link , plus the hover effect of the text should be in green.

Thanks again, when this is done the issue should be closed for good (:

Great job bro (:

**Comment by pro-freelancer** [comment]
This is the best enhancement I can do, I can't push the columns due to avada, is creating them dynamically in absolute  top position. so modifying this is inpossible. I fix it by puting a backgorund opacity to 0.2 and over opacity 0.4, title greay white and centered . This is the best I can do. in case modifying colors you can r-open the ticket. I spend 4 hours to do this shit. Since we using Avada, we can't modify the dynamic generated code.

**Comment by omelki** [comment]
No it's not closed yet before it get fixed, I will find a solution to it right now.

**Comment by omelki** [comment]
OK I found the problem!! we have chosen the wrong template for this page,

to see which one it is, go to: http://demo.theme-fusion.com/
hover on porffolio -> text-layouts -> 4 column text.

**Comment by pro-freelancer** [comment]
Ok, well noted. I just check the text-layout 4, once selected our theme will break. So for now I will posponed this issue, and close others and then get back to it. I put the design I made temperately till I fix this issue for good. PS: can you provide me with the Avada copy to replace this file. to work from a fresh copy. Thanks.

**Comment by pro-freelancer** [comment]
this was fix and set the css upon your feedback. plus if you click the image it open the good link.

**Comment by omelki** [comment]
Ok all is fine - but I have a problem with the last post - leh ma7touta bel zewye 3al yamin malzou2a 3alal title taba3 li fow2a - shaklo khabess el divs bayn ba3don

**Comment by pro-freelancer** [comment]
I Spend 2 hours in searching the cause, and it was an unclosed link in the excerts at the backoffice that was making the page a big mess. Please for next time try not to  make such mistakes cause these kind of errors are hard to detect. I fix the issue and revert the page as it was before the fix I did, no need to my last fix, once the link was closed the page worked as expected.
